DROP TABLE TBL_PLAYER_INFO cascade constraint;
DROP TABLE TBL_HITTER_INFO cascade constraint;

CREATE TABLE TBL_PLAYER_INFO(
	REGISTRATION_CODE CHAR(4) PRIMARY KEY,
	NAME VARCHAR2(18),
	BIRTH_DAY VARCHAR2(8),
	HEIGHT NUMBER(3),
	WEIGHT NUMBER(3)
);

INSERT INTO TBL_PLAYER_INFO VALUES('A001', '김길동', '19900101','','');
INSERT INTO TBL_PLAYER_INFO VALUES('A005', '이길동', '20000101','','');
INSERT INTO TBL_PLAYER_INFO VALUES('B002', '홍길동', '19950101','','');
INSERT INTO TBL_PLAYER_INFO VALUES('A006', '최길동', '19950101','','');

CREATE TABLE TBL_HITTER_INFO(
	REGISTRATION_CODE CHAR(4) PRIMARY KEY,
	GAME_NUMBERS NUMBER(3),
	APPEARANCE NUMBER(3),
	HIT_NUMBERS NUMBER(3),
	HOME_RUNS NUMBER(3),
	PUT_OUT NUMBER(3),
	DOUBLE_PLAY NUMBER(3),
	ERROR_COUNT NUMBER(3),
	CONSTRAINT FK_RG FOREIGN KEY(REGISTRATION_CODE) REFERENCES TBL_PLAYER_INFO(REGISTRATION_CODE)
);

INSERT INTO TBL_HITTER_INFO VALUES('A001', '120', '330', '100', '20', '80', '27', '1');
INSERT INTO TBL_HITTER_INFO VALUES('A005', '110', '300', '110', '30', '60', '5', '2');
INSERT INTO TBL_HITTER_INFO VALUES('B002', '100', '270', '90', '5', '100', '10', '3');

SELECT P.REGISTRATION_CODE, NAME, GAME_NUMBERS, APPEARANCE, HIT_NUMBERS, HOME_RUNS, ROUND(((HIT_NUMBERS+HOME_RUNS)/APPEARANCE)*100,2), PUT_OUT, DOUBLE_PLAY, ERROR_COUNT, (PUT_OUT+DOUBLE_PLAY*2)-ERROR_COUNT*5 FROM TBL_PLAYER_INFO P JOIN TBL_HITTER_INFO H ON P.REGISTRATION_CODE = H.REGISTRATION_CODE WHERE P.REGISTRATION_CODE='A001';

SELECT P.REGISTRATION_CODE, NAME, BIRTH_DAY, HEIGHT, WEIGHT, P.REGISTRATION_CODE, ROUND(((HIT_NUMBERS+HOME_RUNS)/APPEARANCE)*100,2)+((PUT_OUT+DOUBLE_PLAY*2)-ERROR_COUNT*5) AS POINT FROM TBL_PLAYER_INFO P JOIN TBL_HITTER_INFO H ON P.REGISTRATION_CODE = H.REGISTRATION_CODE ORDER BY POINT DESC;

SELECT P.REGISTRATION_CODE, NAME, TO_CHAR(TO_DATE(BIRTH_DAY,'YYYYMMDD'),'YYYY"년"MM"월"DD"일"'), HEIGHT, WEIGHT, P.REGISTRATION_CODE, ROUND(((HIT_NUMBERS+HOME_RUNS)/APPEARANCE)*100,2)+((PUT_OUT+DOUBLE_PLAY*2)-ERROR_COUNT*5) AS POINT FROM TBL_PLAYER_INFO P JOIN TBL_HITTER_INFO H ON P.REGISTRATION_CODE = H.REGISTRATION_CODE ORDER BY POINT DESC;